name: Run Suspicious Activity Script

# Trigger on every push to the repository
on:
  push:
    branches:
      - main  # Change to the branch you want to monitor

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run Python script
      run: python GraphistryChallenge.py
